<?xml version="1.0" encoding="UTF-8"?>
<books>
<book>
<url>${url}</url>
<website>${website}</website>
<title>${title}</title>
<title_en>${title_en}</title_en>
<press>${press}</press>
<pages>${pages}</pages>
<date>${date}</date>
<isbn>${isbn}</isbn>
<version></version>
<binding></binding>
<format></format>
<language></language>
<image_path></image_path>
<author></author>
<translator></translator>
<price_init></price_init>
<price></price>
<book_intro></book_intro>
<author_intro></author_intro>
<series_intro></series_intro>
<category></category>
<tags></tags>
<posts></posts>
<parities></parities>
<level></level>
<rating>
 <level></level>
 <vote></vote>
</rating>
<pic_path></pic_path>
<pic_web_url></pic_web_url>
<words></words>
<content></content>
<series></series>
<note></note>
<c_num></c_num>
<comment>
</comment>
<read_statis>
<want_to_read>0</want_to_read>
<is_reading>0</is_reading>
<has_read>0</has_read>
</read_statis>
<editor_intro></editor_intro>
<media_intro></media_intro>
<preface></preface>
<book_likepart></book_likepart>
</book>
</books>
